import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Script from "next/script";
import { NextFont } from "next/dist/compiled/@next/font";
// const ThemeProvider: ComponentType<{
//     children: ReactNode
// }> = dynamic(() => import('@/contexts/ThemeProvider'), { ssr: false });
import ThemeProvider from "@/contexts/ThemeProvider";
export const metadata: Metadata = {
  title: "SiBasprog",
  description: "Generated by create next app",
};
const poppins: NextFont = Poppins({
  style: 'normal',
  weight: '300',
  subsets: [ 'latin' ]
});
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
      <html lang="en">
        <Script src="https://code.iconify.design/iconify-icon/1.0.8/iconify-icon.min.js"></Script>
        <body className={`${poppins.className} bg-white dark:bg-neutral-950 min-h-screen`}>
            <ThemeProvider>
                { children }
            </ThemeProvider>
        </body>
      </html>
);
}
